### ISSUE TITLE
Demo link doesn't work

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [iravul/SwipeCardview#1]
I'm talking about this:
http://iravul.com/swipecardview/

**Comment by iravul** [comment]
@AndroidDeveloperLB Thank you for feedback. It fixed.

**Comment by AndroidDeveloperLB** [comment]
Still doesn't work. Shows 404 :

![maxthonsnap20170304215911](https://cloud.githubusercontent.com/assets/5357526/23581841/d2e74992-0125-11e7-9e3c-4d88f0eaeec0.png)

**Comment by iravul** [comment]
Hi @AndroidDeveloperLB ,

Please remove the last slash from link. Please use iravul.com/swipecardview. Also, i updated Readme file.

Thank you

**Comment by AndroidDeveloperLB** [comment]
ok now it works fine
